name: Testing
on:
  pull_request:
    branches:
    - master
jobs:
  test:
    name: Testing Swift Package and iOS app
    runs-on: macOS-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v1
      - name: Force XCode 10.1
        run: sudo xcode-select -switch /Applications/Xcode_10.1.app
      - name: Testing iOS app
        run: exec ./.github/scripts/test_app.sh